hero_titre: Bienvenue au Club de Handball Sud Estuaire
hero_sous_titre: >-
  Rejoignez-nous pour partager notre passion du handball et vivre des moments
  inoubliables en communauté. Ensemble, nous cultivons l'esprit d'équipe et
  l'amitié.
hero_cta_texte: Infos Sportives
hero_cta_lien: /infos-sportive
hero_cta_secondaire_texte: Nous rejoindre
hero_cta_secondaire_lien: /inscription
hero_galerie: []
section_features_titre: Rejoignez notre famille de handball
section_features_description: >-
  Au Sud Estuaire Handball Club, nous cultivons un esprit de famille où chaque
  membre est valorisé. Notre passion pour le sport et l'inclusivité font de nous
  un lieu unique pour tous.
section_stats_titre: Nos Performances
section_stats_description: Découvrez les statistiques du club !
testimonial_texte: >-
  Le club Sud Estuaire Handball Club, ce sont des joueuses et joueurs
  d'exception que vous encouragerez toute la saison, mais ce sont surtout des
  bénévoles qui travaillent au quotidien que je tiens vraiment à remercier ici
  pour leur engagement et leur implication.
testimonial_auteur: Frederic et Stephanie
testimonial_role: Co-Président du club
testimonial_photo: /images/testimonial/testimonial_photo.jpeg
section_partenaires_titre: Accompagné par nos partenaires de confiance.
