titre: Boutique SEHC
description: >-
  Équipez-vous aux couleurs du club ! Découvrez notre boutique en ligne pour
  acheter vos maillots, équipements et goodies SEHC. 
helloasso_url: >-
  https://www.helloasso.com/associations/sud-estuaire-handball-club/boutiques/boutique-du-sehc/widget
