hero_titre: Rejoignez le SEHC
hero_description: >-
  Nous avons décidé de dématérialiser entièrement nos dossiers de licence (afin
  de penser à la planète).


  Afin de vous inscrire il vous suffit de cliquer sur le lien ci-dessous et de
  suivre les différentes étapes. Attention, vous ne pourrez faire qu’une seule
  demande de licence à la fois, il vous faudra recommencer votre demande pour
  chaque licence (si plusieurs enfants ou si parent/enfant licenciés par
  exemple).


  Pour le paiement il se fait en ligne via Helloasso, si vous souhaitez payer
  par un autre moyen (liquide ou chèques vacances) il vous faudra bien suivre la
  procédure écrite dans le dossier.


  En cas de soucis concernant le remplissage des dossiers, vous pouvez nous
  joindre par téléphone au 0699490277 ou par mail à l'adresse contact@sehc.fr
hero_image: /images/inscription/hero_image.png
bouton_inscription_texte: S'inscrire maintenant
bouton_inscription_url: https://forms.gle/LwpRpEQjJFNG57Wc6
section_docs_titre: Documents nécessaires
documents: []
section_formulaire_titre: Formulaire d'inscription
helloasso_url: >-
  https://www.helloasso.com/associations/sud-estuaire-handball-club/adhesions/adhesion-pour-la-saison-2026-2027/widget
