entete_titre: Informations Sportives
section_planning_titre: Planning Matchs & Tâches
planning_matchs_image: /images/infos-sportive/planning_matchs_image.png
planning_taches_image: /images/infos-sportive/planning_taches_image.png
section_entrainements_titre: Horaires des Entraînements
section_salles_titre: Nos Gymnases
